### ISSUE TITLE
Make sure the representative detail page is fast

### ISSUE THREAD

**Issue by lauxley** [political-memory/political_memory#132]
The amount of data loaded can be significant, we need to make sure its not too long or handicap mobile users, the design resolved this by using iframe but it would require to split the view in 4, ajax maybe ?

**Comment by jpic** [comment]
@lauxley are you talking about porting 5bc7f370 to v3 which we deployed last sunday ?

**Comment by jpic** [comment]
Note that production is planned for redeploy when Red Hat renews our resource grant.

**Comment by njoyard** [comment]
Yep, fixed by #130
