### ISSUE TITLE
Representative details subpage navigation buttons

### ISSUE THREAD

**Issue by jpic** [political-memory/political_memory#134]
Question for @Ash-Crow : do you think it would be nice to have a rounded border background on representative detail sub page navigation buttons ? Would it make them a bit easier to see ?

![2016-08-09-024715_950x273_scrot](https://cloud.githubusercontent.com/assets/94636/17501104/de08a70a-5ddb-11e6-9602-7e75c013b551.png)

Thanks for your hacking !!

**Comment by njoyard** [comment]
This tab separation is handled in the v3 design ;)
