### ISSUE TITLE
Allowing user to add a public position taken by a representative.

### ISSUE THREAD

**Issue by Psycojoker** [political-memory/political_memory#20]
Interface must be good with clear intent of the designed form. Message like:

    Help use gather the public positions taken by this MEP on <insert stuff> related subjects to contextualize the way he vote. This can be a blog post, a tweet, a public discours, newspaper article etc...

    Submissions are moderated.

**Comment by jpic** [comment]
[Implemented](http://memopol.readthedocs.org/en/pr/usage.html#managing-representative-positions) by @luxcem, nice work !

**Comment by jpic** [comment]
FTR, [tests](https://github.com/political-memory/political_memory/blob/master/representatives_positions/tests/test_functional.py)
