### ISSUE TITLE
Enhance footer

### ISSUE THREAD

**Issue by njoyard** [political-memory/political_memory#71]
Enhance the footer display, add missing links (irc, blog... and parltrack of course)

**Comment by djangocreation** [comment]
have you links ?

**Comment by njoyard** [comment]
At least: 
* Parltrack: http://parltrack.euwiki.org/
* Blog: http://www.memopol.org/

**Comment by djangocreation** [comment]
if branch enhance_footer_tags is merged, we can close issue, isn't it ?
