### ISSUE TITLE
Duplication of MEPS in some views

### ISSUE THREAD

**Issue by okhin** [political-memory/political_memory#93]
When going on the live instance of memopol, there's at least one case where a representative appears multiple times.
For instance, [here](http://lqdn.memopol.eu/legislature/representative/group/European%20Parliament/Confederal%20Group%20of%20the%20European%20United%20Left%20-%20Nordic%20Green%20Left/), for the query displaying the GREENS members there's some duplicates : 
* Marina ALBIOL GUZMÁN
* Martina ANDERSON
* Nikolaos CHOUNTIS

**Comment by njoyard** [comment]
Should be fixed by the merge of #92, reopen this if needed :)

**Comment by njoyard** [comment]
Issue still present in some cases: eg. http://lqdn.memopol.eu/legislature/representative/?chamber=&search=&group=8&country=&active_only=0 (Eleni THEOCHAROUS)
